### ISSUE TITLE
feat: use font awesome icons instead of png assets.

### ISSUE THREAD

**Issue by MayurSMahajan** [MayurSMahajan/transformX#4]
Currently, we use PNG assets for showing icons like record, streak fire, and habit stack. These png icons look blurry on the phone while icons from Flutter's material library look great.

Expected:
1. Add Font Awesome Icon as a dependency in our project.
2. Replace all PNG icons with suitable FontAwesomeIcons.
3. Delete all PNG icons in the assets/icons directory.

Resources:
https://pub.dev/packages/font_awesome_flutter

**Comment by vinaybadgujar102** [comment]
resolved
